=== phenixburn/formationheducap2019/module9[xml]/java-xml-schema-form/repertoire.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/repertoire"
	xmlns:tns="http://www.example.org/repertoire"
	elementFormDefault="qualified">

	<xs:element name="repertoire">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="entree" minOccurs="1"
					maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nom">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="50" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="prenom">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="50" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="adresse">
								<xs:complexType>
									<xs:all>
										<xs:element name="rue" type="xs:string" />
										<xs:element name="ville" type="xs:string" />
										<xs:element name="codepostal" type="xs:string" />
									</xs:all>
									<xs:attribute name="codePays" type="xs:int"
										use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="contact">
								<xs:complexType>
									<xs:all>
										<xs:element name="tel" type="xs:string" />
										<xs:element name="email">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="[a-zA-Z0-9.]+@[a-zA-Z0-9.]+"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:all>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== phenixburn/formationheducap2019/module9[xml]/java-xml-schema-form/repertoire.xml
<?xml version="1.0" encoding="UTF-8"?>
<repertoire xmlns="http://www.example.org/repertoire"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://www.example.org/repertoire repertoire.xsd">

<entree>
	<nom>courtalon</nom>
	<prenom>vincent</prenom>
	<adresse codePays="2">
		<rue>2 rue de la paix</rue>
		<ville>paris</ville>
		<codepostal>75001</codepostal>
	</adresse>
	<contact>
		<tel>0102030405</tel>
		<email>bob@joe.com</email>
	</contact>
</entree>
<entree>
	<nom>bob</nom>
	<prenom>joe</prenom>
	<adresse codePays="2">
		<codepostal>75013</codepostal>
		<rue>73 rue d'ivry</rue>
		<ville>paris</ville>
	</adresse>
	<contact>
		<tel>0154354354</tel>
		<email>ho@ho.com</email>
	</contact>
</entree>
</repertoire>
